[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-SUP3R-US3R
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-SUP3R-US3R
GtkTheme=oomox-SUP3R-US3R
IconTheme=oomox-SUP3R-US3R
MetacityTheme=oomox-SUP3R-US3R
