#! /bin/zsh


bspc monitor -d I II III IV V VI VII VIII IX X 

# ------------
# bspwm config
# ------------
bspc config pointer_follows_focus false
bspc config top_padding 40
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true


#--------------
# Border Colors
#--------------
bspc config border_width	6
bspc config window_gap		7

bspc config focused_border_color        "white"
bspc config focused_locked_border_color "#dc322f"
bspc config active_border_color         "grey"
bspc config active_locked_border_color  "#d33682"
bspc config normal_border_color       "#b58900"
bspc config normal_locked_border_color  "#3F3E3B"
bspc config presel_border_color         "orange"
bspc config urgent_border_color         "#93a1a1"


# ------------------
# Autostart Programs
# ------------------
#panel &
#wmname Bspwm
sxhkd &
#xsetroot -cursor_name left_ptr &
#nitrogen --restore &
#compton --config ~/.config/compton.conf &
#mpd &
yabar -c /home/ghost/.config/yabar/yabar-bspwm.conf &

# -----
# Rules
# -----

#bspc rule -a Firefox desktop=^2
#bspc rule -a Mpv floating=on
#bspc rule -a urxvt floating=on
bspc rule -a thunar floating=on
