version: '3'

services:
    server:
        container_name: 'NODEJS_SERVER_CONTAINER'
        build: .
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
        volumes:
            - ./:/home/app/fullstackapp
            - ./node_modules:/home/app/fullstackapp/node_modules
        depends_on:
            - mongodb
        links:
            - mongodb
        tty: true

    mongodb:
        image: mongo
        container_name: 'MONGODB_CONTAINER'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
