#!/bin/bash

ethernetInterface=`ls /sys/class/net | grep 'e'`
wirelessInterface=`ls /sys/class/net | grep 'w'`

if [ $wirelessInterface ]
then
  device="${BLOCK_INSTANCE:-$wirelessInterface}"
else
  device="${BLOCK_INSTANCE:-$ethernetInterface}"
fi

status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${quality}%"
    echo "${quality}%"
    echo ""

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    echo "on"
    echo "on"
    echo ""
  fi
fi
