#!/bin/bash

SSID_NAME=$(iwgetid -r | tr '[:lower:]' '[:upper:]')

URGENT_VALUE=""

if [[ "${SSID_NAME}" != "" ]]; then
  echo "${SSID_NAME}"
  echo "${SSID_NAME}"
  echo ""

  if [[ "${URGENT_VALUE}" != "" ]] && [[ $(echo "${SSID_NAME}" | grep -we "${URGENT_VALUE}") != "" ]]; then
    exit 33
  fi
fi
